### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by sunzhongliangde** [kingsic/SGSegmentedControl#218]
// 计算所有按钮的文字宽度
[self.titleArr enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        &nbsp; &nbsp;&nbsp;&nbsp; CGSize tempSize = [self P_sizeWithString:obj font:self.configure.titleFont];
        &nbsp;&nbsp; &nbsp;&nbsp; CGFloat tempWidth = tempSize.width;
        &nbsp;&nbsp;&nbsp;&nbsp; self.allBtnTextWidth += tempWidth;
}];

   这里计算总宽度时，假如设置选中的字体与大小，与默认状态下的文字大小不一致的话就会出现计算错误

**Comment by sunzhongliangde** [comment]
`P_layoutSubviews`方法中，开启了`equivalence`，如果`self.allBtnWidth <= self.bounds.size.width`的时候，整个title按钮会被均分，
假设title字体长短差异很大的情况下（比如：12345672342890、1、3、4这种），会导致按钮的换行，应该不要均分button的大小

**Comment by kingsic** [comment]
更新最新版本或OC版本1.7.2 @sunzhongliangde
